### ISSUE TITLE
IndexOutOfBoundsException when no TAG is set in git.

### ISSUE THREAD

**Issue by chris-beep-boop** [corneliudascalu/autoversion#6]
Noticed a small issue that could be reported to the user better.

When the git repo has no TAGs set gradle returns "Index: -1, Size: 1" and you can see this in the logs.
`Caused by: java.lang.IndexOutOfBoundsException: Index: -1, Size: 1
	at com.corneliudascalu.AutoVersion.getCommitCountSinceTag(AutoVersion.kt:29)
	at com.corneliudascalu.AutoVersion.getBuildVersion(AutoVersion.kt:34)
	at com.corneliudascalu.AutoVersion.getVersionName(AutoVersion.kt:11)
	at com.corneliudascalu.AutoVersionPlugin.apply(AutoVersionPlugin.kt:17)
	at com.corneliudascalu.AutoVersionPlugin.apply(AutoVersionPlugin.kt:8)`

A verbose error message would be helpful here to show users "Hey you have no tags, maybe fix that?"

Thanks for the great plugin though it really helps my team keep a consistent version schema.

**Comment by corneliudascalu** [comment]
Thanks for the report. I'll fix it as soon as I can.

**Comment by corneliudascalu** [comment]
Fixed in 0.4
